# Generated by Django 4.2.10 on 2024-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
